#!/bin/bash
#PBS -l walltime=48:00:00
#PBS -l ncpus=32
#PBS -l mem=128GB
#PBS -l jobfs=200GB
#PBS -l wd
#PBS -P y35 
#PBS -q normal 

module load nwchem/7.0.0

mpirun nwchem fexcnw-4.nw > fexcnw-4.out




