#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l ncpus=8
#PBS -l mem=32GB
#PBS -l jobfs=100GB
#PBS -l software=g16
#PBS -l wd
#PBS -P y35 
#PBS -q normal 

module load gaussian
g16 < h-ts-6.txt > h-ts-6.out 2>&1



