#!/bin/bash
#PBS -l walltime=8:00:00
#PBS -l ncpus=16
#PBS -l mem=64GB
#PBS -l jobfs=100GB
#PBS -l software=g16
#PBS -l wd
#PBS -P y35
#PBS -q normal

module load gaussian
g16 < f_sp_-5.txt > f_sp_-5.out 2>&1
g16 < f_sp_-4.txt > f_sp_-4.out 2>&1
g16 < f_sp_-3.txt > f_sp_-3.out 2>&1
g16 < f_sp_-2.txt > f_sp_-2.out 2>&1
g16 < f_sp_-1.txt > f_sp_-1.out 2>&1
g16 < f_sp_0.txt > f_sp_0.out 2>&1
g16 < f_sp_1.txt > f_sp_1.out 2>&1
g16 < f_sp_2.txt > f_sp_2.out 2>&1
g16 < f_sp_3.txt > f_sp_3.out 2>&1
g16 < f_sp_4.txt > f_sp_4.out 2>&1
g16 < f_sp_5.txt > f_sp_5.out 2>&1
